# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_mem {
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/Desktop/bmem.txt}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/Desktop/imem.txt}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/Desktop/dmem.txt}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/Desktop/smem.txt}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/Desktop/reg.txt}
}
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/register_file.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab7/Lab7.srcs/sources_1/imports/new/xycounter.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/new/screenmem.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/new/dmem.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/imports/sources_1/new/datapath.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/new/controller.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab7/Lab7.srcs/sources_1/new/vgatimer.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/new/bmem.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/new/memIO.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/new/clockdiv.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/new/keyboard.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/new/mips.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/new/imem.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab7/Lab7.srcs/sources_1/new/vgadisplaydriver.sv}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/new/top.sv}
}
read_verilog -library xil_defaultlib {
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/fulladder.v}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/adder.v}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/shifter.v}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/logical.v}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/comparator.v}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/addsub.v}
  {C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/sources_1/imports/541Lab/Lab10/Lab10.srcs/sources_1/imports/sources_1/imports/new/ALU.v}
}
read_xdc {{C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/constrs_1/new/FullCPU.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Alchemy/Desktop/541Lab/Lab Project Part A/Lab Project Part A.srcs/constrs_1/new/FullCPU.xdc}}]

synth_design -top top -part xc7a100tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
